services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.22
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch
      - cluster.name=datasearch
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - cluster.initial_master_nodes=elasticsearch
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/esdata

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.22
    ports:
      - "5601:5601"

volumes:
  esdata:
    driver_opts:
      type: "none"
      device: /Users/devih-21/Documents/WorkSpace/extract-pdf/esdata
      o: bind
